// =====================================================
// UPTIME MONITORING CRON JOB
// Runs every 1 minute for continuous monitoring
// PSD-12 §10 - 99.9% SLA Requirement
// =====================================================

import cron from 'node-cron';
import { getUptimeMonitoringService } from '../services/monitoring/uptimeMonitoringService';

// =====================================================
// CRON JOB CONFIGURATION
// =====================================================

/**
 * Continuous Uptime Monitoring
 * 
 * Schedule: Every 1 minute
 * Cron Expression: "* * * * *"
 * 
 * This frequent check ensures:
 * - Quick detection of service outages
 * - Accurate uptime percentage calculation
 * - SLA compliance monitoring (99.9% = max 43 minutes downtime per month)
 */
export const startUptimeMonitoringJob = () => {
  console.log('[Uptime Job] Scheduling uptime monitoring every 1 minute');
  
  const uptimeService = getUptimeMonitoringService();
  
  // Schedule: Run every minute
  cron.schedule('* * * * *', async () => {
    try {
      await uptimeService.performHealthCheck();
    } catch (error) {
      console.error('[Uptime Job] Health check failed:', error);
    }
  }, {
    scheduled: true,
    timezone: 'Africa/Windhoek'
  });
  
  console.log('[Uptime Job] Uptime monitoring job scheduled');
  console.log('[Uptime Job] Health checks will run every 1 minute');
};

/**
 * Daily Summary Generation
 * 
 * Schedule: Every day at 23:55 (5 minutes before midnight)
 * Cron Expression: "55 23 * * *"
 * 
 * Generates daily uptime summary before the day ends
 */
export const startDailySummaryJob = () => {
  console.log('[Uptime Job] Scheduling daily summary generation at 23:55');
  
  const uptimeService = getUptimeMonitoringService();
  
  cron.schedule('55 23 * * *', async () => {
    console.log('[Uptime Job] Generating daily uptime summary...');
    
    try {
      await uptimeService.generateDailySummary();
      console.log('[Uptime Job] Daily summary generated successfully');
    } catch (error) {
      console.error('[Uptime Job] Failed to generate daily summary:', error);
    }
  }, {
    scheduled: true,
    timezone: 'Africa/Windhoek'
  });
  
  console.log('[Uptime Job] Daily summary job scheduled');
};

/**
 * Weekly SLA Compliance Check
 * 
 * Schedule: Every Monday at 08:00
 * Cron Expression: "0 8 * * 1"
 */
export const startSLAComplianceCheckJob = () => {
  console.log('[Uptime Job] Scheduling weekly SLA compliance check every Monday at 08:00');
  
  const uptimeService = getUptimeMonitoringService();
  
  cron.schedule('0 8 * * 1', async () => {
    console.log('[Uptime Job] Checking SLA compliance...');
    
    try {
      const slaStatus = await uptimeService.checkSLACompliance(7); // Last 7 days
      
      console.log('='.repeat(60));
      console.log('WEEKLY SLA COMPLIANCE REPORT');
      console.log('='.repeat(60));
      console.log(`Target Uptime: ${slaStatus.target_uptime}%`);
      console.log(`Actual Uptime: ${slaStatus.actual_uptime.toFixed(2)}%`);
      console.log(`Status: ${slaStatus.is_compliant ? 'MEETING SLA ✓' : 'BELOW SLA ✗'}`);
      console.log('\nComponent Breakdown:');
      slaStatus.components.forEach(c => {
        console.log(`  ${c.component}: ${c.uptime.toFixed(2)}%`);
      });
      console.log('='.repeat(60));
      
      // Alert if not compliant
      if (!slaStatus.is_compliant) {
        console.warn('[Uptime Job] WARNING: SLA compliance below target!');
        // Alert will be generated by the compliance monitoring system
      }
      
    } catch (error) {
      console.error('[Uptime Job] Failed to check SLA compliance:', error);
    }
  }, {
    scheduled: true,
    timezone: 'Africa/Windhoek'
  });
  
  console.log('[Uptime Job] SLA compliance check job scheduled');
};

/**
 * Trigger manual health check
 */
export const triggerManualHealthCheck = async () => {
  console.log('='.repeat(60));
  console.log('MANUAL HEALTH CHECK');
  console.log('Triggered:', new Date().toISOString());
  console.log('='.repeat(60));
  
  const uptimeService = getUptimeMonitoringService();
  
  try {
    const results = await uptimeService.performHealthCheck();
    
    console.log('\n' + '='.repeat(60));
    console.log('HEALTH CHECK RESULTS');
    console.log('='.repeat(60));
    
    results.forEach(result => {
      const statusSymbol = result.status === 'UP' ? '✓' : result.status === 'DOWN' ? '✗' : '⚠';
      console.log(`${statusSymbol} ${result.component.toUpperCase()}: ${result.status} (${result.response_time_ms}ms)`);
      if (result.error_message) {
        console.log(`  Error: ${result.error_message}`);
      }
    });
    
    console.log('='.repeat(60));
    
    return results;
    
  } catch (error) {
    console.error('\nHealth check failed:', error);
    throw error;
  }
};

// CLI execution
if (require.main === module) {
  triggerManualHealthCheck()
    .then(() => {
      console.log('\n✓ Manual health check completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n✗ Manual health check failed:', error);
      process.exit(1);
    });
}
